VP-3593: Enable subscription canceling without specified reason and add default notification templates
VirtoCommerce/vc-module-subscription pull request #43
Opened 2020-09-30 10:38 UTC by eMazeika

2020-09-30 14:48 UTC, akak1977 requested changes

2020-09-30 14:48 UTC, akak1977 commented on src/VirtoCommerce.SubscriptionModule.Web/VirtoCommerce.SubscriptionModule.Web.csproj
> +  <ItemGroup>
Please check templates will be kept after publication and included in artifacts
To include templates use the following code in Web csproj
```

<ItemGroup>
<NotificationTemplates Include="NotificationTemplates/**"/>
</ItemGroup>    
<Target Name="CopyCustomContentOnPublish" AfterTargets="Publish">
  <Copy SourceFiles="@(NotificationTemplates)" DestinationFiles="$(PublishDir)\..\%(Identity)" />
</Target>
```
Take reference to https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-well-known-item-metadata?view=vs-2019

2020-10-01 07:12 UTC, tatarincev approved these changes, later dismissed

2020-10-01 11:07 UTC, akak1977 approved these changes

2020-10-01 11:08 UTC, merged